# ifndef H_DEBUG_FUNCTIONTRACE//INCLUDE GUARD

# define H_DEBUG_FUNCTIONTRACE


# ifdef ALLOW_GRIN_FUNCTION_TRACE

# define START_FUNCTION OUTPUT_DEBUG (PLACE, "FUNCTION_STARTED:");
# define STOP_FUNCTION  OUTPUT_DEBUG (PLACE, "FUNCTION_EXITED:"); return
# define $ OUTPUT_DEBUG (PLACE, "REACHED:");

# else /* ALLOW_GRIN_FUNCTION_TRACE */

# define START_FUNCTION ;
# define STOP_FUNCTION  ;

# endif /* ALLOW_GRIN_FUNCTION_TRACE */



# endif /* H_DEBUG_FUNCTIONTRACE */
